export const IMPORT_TYPES = ['vehicles', 'drivers', 'routes', 'users', 'maintenance']

export const CSV_TEMPLATES = {
  vehicles: {
    label: 'Vehicles',
    filename: 'transitlk-vehicles-sample.csv',
    headers: ['regNumber', 'capacity', 'mileage', 'serviceType', 'status'],
    sampleRows: [
      {
        regNumber: 'NC-6055',
        capacity: '52',
        mileage: '92000',
        serviceType: 'express',
        status: 'available',
      },
      {
        regNumber: 'NC-7123',
        capacity: '48',
        mileage: '156400',
        serviceType: 'ordinary',
        status: 'available',
      },
    ],
    hints: 'serviceType: express | ordinary | semi-luxury. status: available | in-service | maintenance',
  },
  drivers: {
    label: 'Drivers',
    filename: 'transitlk-drivers-sample.csv',
    headers: [
      'name',
      'licenseNo',
      'email',
      'password',
      'contactNo',
      'workingHours',
      'licenseExpiry',
      'status',
    ],
    sampleRows: [
      {
        name: 'Sample Driver',
        licenseNo: 'B4521987',
        email: 'driver.sample@transitlk.lk',
        password: '',
        contactNo: '0771234567',
        workingHours: '05:00-18:00',
        licenseExpiry: '2028-12-31',
        status: 'available',
      },
      {
        name: 'Kamal Silva',
        licenseNo: 'B3891042',
        email: '',
        password: '',
        contactNo: '0772345678',
        workingHours: '06:00-20:00',
        licenseExpiry: '2027-06-30',
        status: 'available',
      },
    ],
    hints: 'status: available | on-duty | on-leave | off-duty. email/password optional for portal login.',
  },
  routes: {
    label: 'Routes',
    filename: 'transitlk-routes-sample.csv',
    headers: [
      'routeNo',
      'startPoint',
      'endPoint',
      'viaDescription',
      'distance',
      'serviceType',
      'status',
    ],
    sampleRows: [
      {
        routeNo: '556',
        startPoint: 'Matale',
        endPoint: 'Kurunegala',
        viaDescription: '',
        distance: '51.0',
        serviceType: 'express',
        status: 'active',
      },
      {
        routeNo: '593',
        startPoint: 'Matale',
        endPoint: 'Kandy',
        viaDescription: 'via Warakamura',
        distance: '26.2',
        serviceType: 'ordinary',
        status: 'active',
      },
    ],
    hints: 'status: active | inactive | draft. distance in km. Route name is built from start/end.',
  },
  users: {
    label: 'Staff users',
    filename: 'transitlk-users-sample.csv',
    headers: ['name', 'email', 'password', 'role', 'isActive'],
    sampleRows: [
      {
        name: 'Fleet Manager',
        email: 'fleet@transitlk.com',
        password: 'ChangeMe123',
        role: 'fleet_manager',
        isActive: 'true',
      },
      {
        name: 'Transport Scheduler',
        email: 'scheduler@transitlk.com',
        password: 'ChangeMe123',
        role: 'transport_scheduler',
        isActive: 'true',
      },
    ],
    hints:
      'role: transport_scheduler | fleet_manager | depot_manager (administrator for superadmin only). Assigns to your depot.',
  },
  maintenance: {
    label: 'Maintenance logs',
    filename: 'transitlk-maintenance-sample.csv',
    headers: [
      'regNumber',
      'service_date',
      'description',
      'cost',
      'status',
      'startedAt',
      'completedAt',
    ],
    sampleRows: [
      {
        regNumber: 'NC-9912',
        service_date: '2026-06-02',
        description: 'Brake pad & disc replacement',
        cost: '42000',
        status: 'completed',
        startedAt: '2026-06-02',
        completedAt: '2026-06-05',
      },
      {
        regNumber: 'NC-5124',
        service_date: '2026-06-07',
        description: 'Oil change & filter replacement',
        cost: '12000',
        status: 'in-progress',
        startedAt: '2026-06-07',
        completedAt: '',
      },
    ],
    hints:
      'regNumber must match a vehicle in your depot. status: scheduled | in-progress | completed | cancelled. Dates: YYYY-MM-DD.',
  },
}
