/** Canonical roles aligned with SRMSS actors */
export const ROLES = {
  ADMINISTRATOR: 'administrator',
  TRANSPORT_SCHEDULER: 'transport_scheduler',
  FLEET_MANAGER: 'fleet_manager',
  DEPOT_MANAGER: 'depot_manager',
  DRIVER: 'driver',
}

export const STAFF_ROLES = [
  ROLES.TRANSPORT_SCHEDULER,
  ROLES.FLEET_MANAGER,
  ROLES.DEPOT_MANAGER,
]

/** API route groups → allowed roles */
export const API_ACCESS = {
  routes: [ROLES.ADMINISTRATOR, ROLES.TRANSPORT_SCHEDULER],
  schedules: [ROLES.ADMINISTRATOR, ROLES.TRANSPORT_SCHEDULER, ROLES.DEPOT_MANAGER, ROLES.DRIVER],
  reports: [ROLES.ADMINISTRATOR, ROLES.TRANSPORT_SCHEDULER, ROLES.DEPOT_MANAGER],
  buses: [ROLES.ADMINISTRATOR, ROLES.FLEET_MANAGER],
  drivers: [ROLES.ADMINISTRATOR, ROLES.FLEET_MANAGER],
  maintenance: [ROLES.ADMINISTRATOR, ROLES.FLEET_MANAGER],
  fuel: [ROLES.ADMINISTRATOR, ROLES.FLEET_MANAGER],
  depots: [ROLES.ADMINISTRATOR],
  admins: [ROLES.ADMINISTRATOR],
}
